const KEY='alhawary_demo_users_v1', SESSION='alhawary_session_v1';
const seed=[{id:'1',title:'مقدمة في المادة',description:'درس تجريبي يمكنك استبداله من لوحة الإدارة.',videoUrl:''},{id:'2',title:'الدرس الثاني',description:'مثال على درس آخر داخل المنصة.',videoUrl:''}];
let users=JSON.parse(localStorage.getItem(KEY)||'[]');
let lessons=JSON.parse(localStorage.getItem('alhawary_lessons')||'null')||seed;
function save(){localStorage.setItem(KEY,JSON.stringify(users));localStorage.setItem('alhawary_lessons',JSON.stringify(lessons))}
function showAuth(mode){document.getElementById('authModal').classList.remove('hidden');renderAuth(mode)}
function hideAuth(){document.getElementById('authModal').classList.add('hidden')}
function renderAuth(mode){
 const c=document.getElementById('authContent');
 c.innerHTML=mode==='login'?`<h2>تسجيل الدخول</h2><p class="muted">ادخل بحسابك للمتابعة.</p><form class="form" onsubmit="login(event)"><label>البريد الإلكتروني</label><input id="email" type="email" required><label>كلمة المرور</label><input id="password" type="password" required><button class="btn">دخول</button></form><p id="authMsg"></p><p>ليس لديك حساب؟ <button class="linkbtn" onclick="renderAuth('register')">إنشاء حساب</button></p>`:
 `<h2>حساب مجاني</h2><p class="muted">أنشئ حسابك وابدأ التعلم.</p><form class="form" onsubmit="register(event)"><label>الاسم</label><input id="name" required><label>البريد الإلكتروني</label><input id="email" type="email" required><label>كلمة المرور</label><input id="password" type="password" minlength="6" required><button class="btn">إنشاء الحساب</button></form><p id="authMsg"></p><p>لديك حساب؟ <button class="linkbtn" onclick="renderAuth('login')">تسجيل الدخول</button></p>`;
}
function register(e){e.preventDefault();const name=document.getElementById('name').value.trim(),email=document.getElementById('email').value.trim().toLowerCase(),password=document.getElementById('password').value;if(users.some(u=>u.email===email)){return msg('الحساب موجود بالفعل.','error')}users.push({name,email,password,completed:[]});save();localStorage.setItem(SESSION,email);hideAuth();openDashboard()}
function login(e){e.preventDefault();const email=document.getElementById('email').value.trim().toLowerCase(),password=document.getElementById('password').value,u=users.find(x=>x.email===email&&x.password===password);if(!u)return msg('بيانات الدخول غير صحيحة.','error');localStorage.setItem(SESSION,email);hideAuth();openDashboard()}
function msg(t,cl){const x=document.getElementById('authMsg');x.textContent=t;x.className=cl}
function current(){return users.find(u=>u.email===localStorage.getItem(SESSION))}
function openDashboard(){const u=current();if(!u)return;document.getElementById('dashboard').classList.remove('hidden');renderDashboard()}
function hideDashboard(){document.getElementById('dashboard').classList.add('hidden')}
function renderDashboard(){const u=current();const c=document.getElementById('dashboardContent');c.innerHTML=`<h2>مرحبًا ${esc(u.name)}</h2><p class="muted">حساب طالب مجاني</p><div class="dash-grid"><div class="card"><h3>دروسي</h3><p>تم إكمال ${u.completed.length} من ${lessons.length} درس.</p><button class="btn" onclick="renderStudentLessons()">عرض الدروس</button></div><div class="card"><h3>الإدارة التجريبية</h3><p>لوحة الإدارة في هذه النسخة محلية للتجربة فقط.</p><button class="btn ghost" onclick="renderAdmin()">فتح لوحة الإدارة</button></div></div><br><button class="btn danger" onclick="logout()">تسجيل الخروج</button>`}
function renderStudentLessons(){const c=document.getElementById('dashboardContent');c.innerHTML='<h2>الدروس</h2>'+lessons.map(l=>`<div class="card" style="margin:10px 0"><h3>${esc(l.title)}</h3><p>${esc(l.description||'')}</p>${l.videoUrl?`<button class="btn" onclick="watch('${encodeURIComponent(l.id)}')">مشاهدة الدرس</button>`:'<span class="muted">لم تتم إضافة فيديو بعد</span>'}</div>`).join('')+'<button class="linkbtn" onclick="renderDashboard()">رجوع</button>'}
function watch(id){const l=lessons.find(x=>x.id===decodeURIComponent(id));const c=document.getElementById('dashboardContent');c.innerHTML=`<h2>${esc(l.title)}</h2><iframe class="video" src="${esc(l.videoUrl)}" allowfullscreen></iframe><p>${esc(l.description||'')}</p><button class="btn" onclick="complete('${l.id}')">تم الانتهاء من الدرس</button> <button class="linkbtn" onclick="renderStudentLessons()">رجوع</button>`}
function complete(id){const u=current();if(!u.completed.includes(id))u.completed.push(id);save();renderStudentLessons()}
function renderAdmin(){const c=document.getElementById('dashboardContent');c.innerHTML=`<h2>لوحة الإدارة التجريبية</h2><p class="muted">للتجربة على جهازك فقط. في النسخة المنشورة يجب استبدال التخزين المحلي بـ Firebase/Supabase وصلاحيات خادم.</p><form class="form" onsubmit="addLesson(event)"><label>اسم الدرس</label><input id="lt" required><label>الوصف</label><textarea id="ld"></textarea><label>رابط الفيديو المضمّن</label><input id="lv" placeholder="https://..."><button class="btn">إضافة درس</button></form><hr>${lessons.map(l=>`<p><b>${esc(l.title)}</b> <button class="linkbtn" onclick="deleteLesson('${l.id}')">حذف</button></p>`).join('')}<button class="linkbtn" onclick="renderDashboard()">رجوع</button>`}
function addLesson(e){e.preventDefault();lessons.push({id:Date.now().toString(),title:document.getElementById('lt').value,description:document.getElementById('ld').value,videoUrl:document.getElementById('lv').value});save();renderAdmin();renderPublic()}
function deleteLesson(id){lessons=lessons.filter(l=>l.id!==id);save();renderAdmin();renderPublic()}
function logout(){localStorage.removeItem(SESSION);hideDashboard()}
function renderPublic(){const box=document.getElementById('lessons');box.innerHTML=lessons.map(l=>`<div class="card"><h3>${esc(l.title)}</h3><p>${esc(l.description||'')}</p><button class="btn" onclick="showAuth('login')">سجّل الدخول للمشاهدة</button></div>`).join('');document.getElementById('courseCount').textContent=`${lessons.length} دروس`}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
renderPublic();save();
